### ISSUE TITLE
What will be there in paybill number & Passkey

### ISSUE THREAD

**Issue by harshj-magneto** [Fellojuma/Magento-2-Mpesa-Express-Module#12]
How to get playbill number and passkey and also facing issue while placing an order please check below screenshot for reference.
![Screenshot from 2020-11-24 21-40-41](https://user-images.githubusercontent.com/74974768/100120288-cd0f3080-2e9d-11eb-8b3d-db3a05083d08.png)
![Screenshot from 2020-11-24 21-40-35](https://user-images.githubusercontent.com/74974768/100120296-ce405d80-2e9d-11eb-9f6d-a68c6b6ec3c3.png)

**Comment by Fellojuma** [comment]
Hi you can get a test paybill and passkey from http://developer.safaricom.co.ke/ 

In case you need production paybill and passkey kindly apply https://m-pesaforbusiness.co.ke/LNM/

**Comment by harshj-magneto** [comment]
but can you please provide me the solution for the error mentioned in the screenshot
