### ISSUE TITLE
Invalid Access Token 

### ISSUE THREAD

**Issue by rakeshdonga** [Fellojuma/Magento-2-Mpesa-Express-Module#2]
i have use this extension but when place order after check my json  below error  showing what is problem?

Array 
( [requestId] => 23345-510564-1 
[errorCode] => 400.002.02
[errorMessage] => Invalid BusinessShortCode
 )

**Comment by crim3hound** [comment]
@rakeshdonga there is probably a mismatch between the credentials you are using and the `BusinessShortCode` or `Paybill number`.

**Comment by rakeshdonga** [comment]
thanks for replay
my credential is right
