### ISSUE TITLE
PHP Fatal error:  Call to undefined method getUrl()

### ISSUE THREAD

**Issue by crim3hound** [Fellojuma/Magento-2-Mpesa-Express-Module#3]
Getting the following fatal error which prevents the STKPush from completing:

`PHP Fatal error:  Uncaught Error: Call to undefined method Safaricom\Mpesa\Controller\Mpesa\Startpayment\Interceptor::getUrl() in app/code/Safaricom/Mpesa/Controller/Mpesa/Startpayment.php:70`

What could be the issue?

**Comment by Fellojuma** [comment]
This depends on what version of magento 2 you are running on. To solve it you need to get the base url of your setup and append the listener url.

use Magento\Store\Model\StoreManagerInterface;

$base_url = $this->storeManager->getStore()->getBaseUrl();

$callback_url = $base_url.' safaricommpesa/mpesa/stkpushlistener';
