### ISSUE TITLE
What do we enter as Mpesa Request Url? 

### ISSUE THREAD

**Issue by kailikia** [Fellojuma/Magento-2-Mpesa-Express-Module#9]
I am using magento 2. 2.5 installation for this and there is a required field called Mpesa Request Url.. What should we fill here?
Thanks in advance

**Comment by Fellojuma** [comment]
Hi
If your service is live use **https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest** 
but if its on Mpesa sandbox use **https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest**

**Comment by kailikia** [comment]
Thank you
